# Generated by Django 3.2 on 2022-06-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('company_ticker', models.CharField(max_length=200, verbose_name='company ticker')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ESG_score', models.PositiveSmallIntegerField(verbose_name='ESG score')),
                ('environment', models.PositiveSmallIntegerField(verbose_name='environment')),
                ('social', models.PositiveSmallIntegerField(verbose_name='social')),
                ('governance', models.PositiveSmallIntegerField(verbose_name='governance')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='rank')),
                ('total_industries', models.PositiveSmallIntegerField(verbose_name='total industries')),
                ('company_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='company.company')),
            ],
        ),
    ]
