# Generated by Django 3.2 on 2022-06-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'company profile', 'verbose_name_plural': 'companies profile'},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_ticker',
            field=models.CharField(max_length=200, unique=True, verbose_name='company ticker'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
    ]
