# Generated by Django 3.2 on 2022-06-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220604_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company_profile',
            new_name='company',
        ),
    ]
